import dotenv from 'dotenv';

dotenv.config();

// export const {
//   WEBHOOK_VERIFY_TOKEN,
//   API_TOKEN,
//   BUSINESS_PHONE,
//   API_VERSION,
//   PORT,
//   BASE_URL,
//   TYPE_CREDENTIALS,
//   PROJECT_ID_CREDENTIALS,
//   PRIVATE_KEY_ID_CREDENTIALS,
//   PRIVATE_KEY_CREDENTIALS,
//   CLIENT_EMAIL_CREDENTIALS,
//   CLIENT_ID_CREDENTIALS,
//   AUTH_URI_CREDENTIALS,
//   TOKEN_URI_CREDENTIALS,
//   AUTH_PROVIDER_X509_CERT_URL_CREDENTIALS,
//   CLIENT_X509_CERT_URL_CREDENTIALS,
//   UNIVERSAL_DOMAIN_CREDENTIALS
// } = process.env;

export default {
  WEBHOOK_VERIFY_TOKEN: process.env.WEBHOOK_VERIFY_TOKEN,
  API_TOKEN: process.env.API_TOKEN,
  BUSINESS_PHONE: process.env.BUSINESS_PHONE,
  API_VERSION: process.env.API_VERSION,
  PORT: process.env.PORT || 3000,
  BASE_URL: process.env.BASE_URL,
  TYPE_CREDENTIALS: process.env.TYPE_CREDENTIALS,
  PROJECT_ID_CREDENTIALS: process.env.PROJECT_ID_CREDENTIALS,
  PRIVATE_KEY_ID_CREDENTIALS: process.env.PRIVATE_KEY_ID_CREDENTIALS,
  PRIVATE_KEY_CREDENTIALS: process.env.PRIVATE_KEY_CREDENTIALS,
  CLIENT_EMAIL_CREDENTIALS: process.env.CLIENT_EMAIL_CREDENTIALS,
  CLIENTE_ID_CREDENTIALS: process.env.CLIENTE_ID_CREDENTIALS,
  AUTH_URI_CREDENTIALS: process.env.AUTH_URI_CREDENTIALS,
  TOKEN_URI_CREDENTIALS: process.env.TOKEN_URI_CREDENTIALS,
  AUTH_PROVIDER_X509_CERT_URL_CREDENTIALS: process.env.AUTH_PROVIDER_X509_CERT_URL_CREDENTIALS,
  CLIENT_X509_CERT_URL_CREDENTIALS: process.env.CLIENT_X509_CERT_URL_CREDENTIALS,
  UNIVERSAL_DOMAIN_CREDENTIALS: process.env.UNIVERSAL_DOMAIN_CREDENTIALS,
  SPREADSHEET_ID_CREDENTIALS: process.env.SPREADSHEET_ID_CREDENTIALS
};